import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container/Container";
import Button from "../components/Button/Button";
import Header from "../components/Header/Header";
import styles from "../styles/Home.module.scss";
import products from "../data/products.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fran_The_Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Container>
          <h1>Fran_The_Dev Climbing and Code Swag Store</h1>
          <h2>Available Gear And Swag</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    width="1500"
                    height="1200"
                    src={product.image}
                    alt={`Gear and Swag of ${product.title}`}
                  />
                  <h3 className={styles.productTitle}>{product.title}</h3>
                  <p className={styles.productPrice}>${product.price}</p>
                  <p>
                    <Button>Add To Cart</Button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Fran_The_Dev Store, {new Date().getFullYear()}
      </footer>
    </div>
  );
}
