import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container/Container";
import Button from "../components/Button/Button";
import Header from "../components/Header/Header";
import styles from "../styles/Home.module.scss";
import products from "../data/products.json";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fran_The_Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css"
        />
      </Head>
      <Header />
      <main className={styles.main}>
        <Container>
          <h1>Fran_The_Dev Climbing and Code Swag Store</h1>
          <h2>Available Gear And Swag</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    width="1500"
                    height="1200"
                    src={product.image}
                    alt={`Gear and Swag of ${product.title}`}
                  />
                  <h3 className={styles.productTitle}>{product.title}</h3>
                  <p className={styles.productPrice}>${product.price}</p>
                  <p>
                    <Button
                      className="snipcart-add-item"
                      data-item-id={product.id}
                      data-item-price={product.price}
                      data-item-url="/"
                      data-item-description=""
                      data-item-image={product.image}
                      data-item-name={product.title}
                    >
                      Add to cart
                    </Button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Fran_The_Dev Store, {new Date().getFullYear()}
      </footer>

      <Script src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js" />
      <div
        hidden
        id="snipcart"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
      ></div>
    </div>
  );
}
